#!/usr/bin/env bash
#a Bash script that displays the PID, along with the process name, of all processes whose name contains the word bash. The output for each process should be on a new line, in the format PID process_name.
pgrep -l bash
