#!/usr/bin/env bash
#a Bash script that displays numbers from 1 to 20. For specific iterations, it should display additional “bad luck” messages:

    #Displays 4 and then “bad luck from China” for the 4th loop iteration.
    #Displays 9 and then “bad luck from Japan” for the 9th loop iteration.
    #Displays 17 and then “bad luck from Italy” for the 17th loop iteration.
    #For all other iterations, only the number should be displayed.
export i=1
while [ $i -le 20 ]; do
    case "$i" in
    5)
        echo "bad luck from China"
    ;;
    case "$i" in
    10)
        echo "bad luck from Japan"
    ;;
    case "$i" in
    18)
        echo "bad luck from Italy"
    ;;
  echo $i
  i=$((i + 1))
done
  
