#!/usr/bin/env bash
#a Bash script that displays:

    #The content of the current directory.
    #In a list format (one item per line).
    #Where only the part of the name after the first dash (-) is displayed (refer to the example for clarity).
export var
for var in 
